public with sharing class Constant {
  public static final String OFFER_CONTROLLER_ERROR_MESSAGE = 'Car is already physically listed';
  public static final String SALON_CONTROLLER_ERROR_MESSAGE_WAREHOUSE = 'There can be only one warehouse related to specific account';
  public static final String SALON_CONTROLLER_ERROR_MESSAGE_PARKING = 'There are more vehicles than desired parking spots';
  public static final String VEHICLE_CONTROLLER_ERROR_MESSAGE = 'There are not enough parking spots for vehicles in this salon ';
  public static final String SALON_STATUS = 'Closed';
  public static final String SALON_STATUS_OPEN = 'Open';
}
