public with sharing class Constant {
  public static final String offerControllerErrorMessage = 'Car is already physically listed';
  public static final String salonControllerErrorMessageWarehouse = 'There can be only one warehouse related to specific account';
  public static final String salonControllerErrorMessageParking = 'There are more vehicles than desired parking spots';
  public static final String vehicleControllerErrorMessage = 'There are not enough parking spots for vehicles in this salon ';
}
