public with sharing class Constant {
    public static final String ENDPOINT = 'https://wise-shark-ppge52-dev-ed.my.salesforce.com/services/';
    public static final String AUTHORIZATION = 'Authorization';
    public static final String CONTENT_TYPE = 'Content-Type';
    public static final String APPLICATION = 'application/json';
    public static final String ACCEPT = 'accept';
    public static final String REST_GET = 'GET';
    public static final String REST_POST = 'POST';
    public static final String CLIENT_ID = '3MVG9SOw8KERNN092PrKygczI_Uh6NRAls6AVkV7rUyyXA9Waqjd23oVTIrd7rXaVQcl9oJtNO7zlPqNZ3LOz';
    public static final String CLIENT_SECRET ='DC167EA1890CD029730B596450F872C986248916618B494BE7F5BBF5FB47F1CA';
    public static final String LOGIN = 'dominiak123@wise-shark-ppge52.com';
    public static final String PASSWORD = 'Podkladka1';
}
